CREATE TABLE `users` (
  `id` CHAR(36) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `role` ENUM('ADMINISTRATOR', 'SALES_EXECUTIVE') NOT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `token_version` INT NOT NULL DEFAULT 1,
  `last_login_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_key` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `refresh_sessions` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `token_hash` VARCHAR(255) NOT NULL,
  `user_agent` VARCHAR(512) NOT NULL DEFAULT '',
  `ip_address` VARCHAR(45) NOT NULL DEFAULT '',
  `expires_at` DATETIME(6) NOT NULL,
  `revoked_at` DATETIME(6) NULL,
  `revoke_reason` VARCHAR(255) NULL,
  `replaced_by_session_id` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `refresh_sessions_user_id_expires_at_idx` (`user_id`, `expires_at`),
  KEY `refresh_sessions_expires_at_idx` (`expires_at`),
  CONSTRAINT `refresh_sessions_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `prospects` (
  `id` CHAR(36) NOT NULL,
  `google_place_id` VARCHAR(191) NOT NULL,
  `place_name` VARCHAR(255) NOT NULL,
  `formatted_address` TEXT NOT NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `place_category` VARCHAR(191) NOT NULL,
  `industry_group` VARCHAR(191) NOT NULL DEFAULT 'Other',
  `place_types` JSON NOT NULL DEFAULT (JSON_ARRAY()),
  `phone_number` VARCHAR(64) NULL,
  `website_url` VARCHAR(2048) NULL,
  `google_maps_url` VARCHAR(2048) NULL,
  `assigned_sales_executive_id` CHAR(36) NOT NULL,
  `visit_notes` TEXT NOT NULL DEFAULT (''),
  `follow_up_notes` TEXT NOT NULL DEFAULT (''),
  `status` ENUM('NEW_LEAD', 'CONTACTED', 'INTERESTED', 'QUALIFIED', 'PROPOSAL_SENT', 'NEGOTIATION', 'WON', 'LOST', 'CONVERTED') NOT NULL DEFAULT 'NEW_LEAD',
  `converted_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `prospects_google_place_id_key` (`google_place_id`),
  KEY `prospects_assigned_sales_executive_id_status_idx` (`assigned_sales_executive_id`, `status`),
  KEY `prospects_status_created_at_idx` (`status`, `created_at`),
  KEY `prospects_industry_group_status_idx` (`industry_group`, `status`),
  CONSTRAINT `prospects_assigned_sales_executive_id_fkey` FOREIGN KEY (`assigned_sales_executive_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `prospect_status_history` (
  `id` CHAR(36) NOT NULL,
  `prospect_id` CHAR(36) NOT NULL,
  `from_status` ENUM('NEW_LEAD', 'CONTACTED', 'INTERESTED', 'QUALIFIED', 'PROPOSAL_SENT', 'NEGOTIATION', 'WON', 'LOST', 'CONVERTED') NULL,
  `to_status` ENUM('NEW_LEAD', 'CONTACTED', 'INTERESTED', 'QUALIFIED', 'PROPOSAL_SENT', 'NEGOTIATION', 'WON', 'LOST', 'CONVERTED') NOT NULL,
  `changed_by_user_id` CHAR(36) NOT NULL,
  `notes` TEXT NOT NULL DEFAULT (''),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `prospect_status_history_prospect_id_created_at_idx` (`prospect_id`, `created_at`),
  KEY `prospect_status_history_changed_by_user_id_idx` (`changed_by_user_id`),
  CONSTRAINT `prospect_status_history_prospect_id_fkey` FOREIGN KEY (`prospect_id`) REFERENCES `prospects` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `prospect_status_history_changed_by_user_id_fkey` FOREIGN KEY (`changed_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `parent_companies` (
  `id` CHAR(36) NOT NULL,
  `parent_code` VARCHAR(32) NOT NULL COLLATE utf8mb4_0900_as_cs,
  `name` VARCHAR(255) NOT NULL,
  `address_mode` VARCHAR(64) NOT NULL DEFAULT 'MANUAL',
  `province` VARCHAR(191) NOT NULL DEFAULT '',
  `district` VARCHAR(191) NOT NULL DEFAULT '',
  `sub_district` VARCHAR(191) NOT NULL DEFAULT '',
  `village` VARCHAR(191) NOT NULL DEFAULT '',
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `preview_address` TEXT NOT NULL DEFAULT (''),
  `company_contacts` JSON NOT NULL DEFAULT (JSON_ARRAY()),
  `npwp_name` VARCHAR(255) NOT NULL DEFAULT '',
  `npwp_address` TEXT NOT NULL DEFAULT (''),
  `npwp_number` VARCHAR(64) NOT NULL DEFAULT '',
  `term_of_payment` VARCHAR(191) NOT NULL DEFAULT '',
  `kam_assignments` JSON NOT NULL DEFAULT (JSON_ARRAY()),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `parent_companies_parent_code_key` (`parent_code`),
  KEY `parent_companies_name_idx` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `customer_sites` (
  `id` CHAR(36) NOT NULL,
  `customer_code` VARCHAR(64) NOT NULL COLLATE utf8mb4_0900_as_cs,
  `parent_company_id` CHAR(36) NOT NULL,
  `source_prospect_id` CHAR(36) NULL,
  `source_google_place_id` VARCHAR(191) NULL,
  `name` VARCHAR(255) NOT NULL,
  `segment` VARCHAR(191) NOT NULL,
  `category` VARCHAR(191) NOT NULL,
  `address_mode` VARCHAR(64) NOT NULL DEFAULT 'MANUAL',
  `province` VARCHAR(191) NOT NULL DEFAULT '',
  `district` VARCHAR(191) NOT NULL DEFAULT '',
  `sub_district` VARCHAR(191) NOT NULL DEFAULT '',
  `village` VARCHAR(191) NOT NULL DEFAULT '',
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `preview_address` TEXT NOT NULL,
  `site_contacts` JSON NOT NULL DEFAULT (JSON_ARRAY()),
  `ppn` VARCHAR(64) NOT NULL DEFAULT '',
  `id_tku_number` VARCHAR(64) NOT NULL DEFAULT '',
  `nik` VARCHAR(64) NOT NULL DEFAULT '',
  `shipment_cost` VARCHAR(191) NOT NULL DEFAULT '',
  `invoice_type` VARCHAR(191) NOT NULL DEFAULT '',
  `bank_account` VARCHAR(191) NOT NULL DEFAULT '',
  `bill_to_source` VARCHAR(191) NOT NULL DEFAULT '',
  `ship_to_source` VARCHAR(191) NOT NULL DEFAULT '',
  `billing_address_preview` TEXT NOT NULL DEFAULT (''),
  `shipping_address_preview` TEXT NOT NULL DEFAULT (''),
  `sales_executive_id` CHAR(36) NOT NULL,
  `sales_assignments` JSON NOT NULL DEFAULT (JSON_ARRAY()),
  `converted_at` DATETIME(6) NOT NULL,
  `converted_by_admin_id` CHAR(36) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `customer_sites_customer_code_key` (`customer_code`),
  KEY `customer_sites_sales_executive_id_converted_at_idx` (`sales_executive_id`, `converted_at`),
  KEY `customer_sites_parent_company_id_idx` (`parent_company_id`),
  KEY `customer_sites_source_prospect_id_idx` (`source_prospect_id`),
  KEY `customer_sites_converted_by_admin_id_idx` (`converted_by_admin_id`),
  CONSTRAINT `customer_sites_parent_company_id_fkey` FOREIGN KEY (`parent_company_id`) REFERENCES `parent_companies` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `customer_sites_sales_executive_id_fkey` FOREIGN KEY (`sales_executive_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `customer_sites_converted_by_admin_id_fkey` FOREIGN KEY (`converted_by_admin_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `prospect_visits` (
  `id` CHAR(36) NOT NULL,
  `prospect_id` CHAR(36) NOT NULL,
  `sales_executive_id` CHAR(36) NOT NULL,
  `check_in_at` DATETIME(6) NOT NULL,
  `check_in_latitude` DOUBLE NOT NULL,
  `check_in_longitude` DOUBLE NOT NULL,
  `check_out_at` DATETIME(6) NULL,
  `check_out_latitude` DOUBLE NULL,
  `check_out_longitude` DOUBLE NULL,
  `selfie_reference` VARCHAR(2048) NOT NULL DEFAULT '',
  `visit_notes` TEXT NOT NULL DEFAULT (''),
  `follow_up_notes` TEXT NOT NULL DEFAULT (''),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `open_visit_prospect_id` CHAR(36) GENERATED ALWAYS AS (CASE WHEN `check_out_at` IS NULL THEN `prospect_id` ELSE NULL END) STORED,
  PRIMARY KEY (`id`),
  KEY `prospect_visits_prospect_id_check_in_at_idx` (`prospect_id`, `check_in_at`),
  KEY `prospect_visits_sales_executive_id_check_in_at_idx` (`sales_executive_id`, `check_in_at`),
  UNIQUE KEY `prospect_visits_one_open_visit_idx` (`open_visit_prospect_id`),
  CONSTRAINT `prospect_visits_prospect_id_fkey` FOREIGN KEY (`prospect_id`) REFERENCES `prospects` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `prospect_visits_sales_executive_id_fkey` FOREIGN KEY (`sales_executive_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `code_counters` (
  `name` VARCHAR(64) NOT NULL COLLATE utf8mb4_0900_as_cs,
  `current_value` BIGINT NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
